### ISSUE TITLE
Genotyping technology field needs cleaning up

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/xgwas-curator-tasks#12]
Open targets reported several studies from 2 PMIDs have trait information or other erroneous information in the genotyping technology field, which has been entered in the additional array information field. This needs cleaning up.  

Affected studies are: 

PMID33430342, Younes et al
GCST90093097
GCST90093098
GCST90093099
GCST90093100
GCST90093101

PMID33693786, Sun et al
GCST90188372
GCST90188373
GCST90188374
GCST90188375
GCST90188376
GCST90188377
GCST90188378
GCST90188379
GCST90188380
GCST90188383
GCST90002413
GCST90188385
GCST90188386
GCST90188387

**Comment by Santhi1901** [comment]
completed, the changes were made only in the curation db, not through depo-curation. Have made a note of the same in the notes.

**Comment by ljwh2** [comment]
@Santhi1901 to confirm changes are visible in production, then close ticket

**Comment by Santhi1901** [comment]
Changes visible in the production
