### ISSUE TITLE
Trait labels switched in PMID 35760791 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/xgwas-curator-tasks#14]
User email 2/1/23

> It has come to my attention that the reported trait labels for two of the studies (GCST90101829 and GCST90101825) associated with publication PMID: 35760791 (https://www.ebi.ac.uk/gwas/publications/35760791) have their Reported trait labels swapped. Specifically, the studies currently have the following reported trait labels:
> 
> GCST90101825: Cryptic phenotype that captures autosomal dominant polycystic kidney disease severity
> GCST90101829: Cryptic phenotype that captures alpha-1-antitrypsin deficiency severity
> 
> They should be switched to the following:
> 
> GCST90101829: Cryptic phenotype that captures autosomal dominant polycystic kidney disease severity
> GCST90101825: Cryptic phenotype that captures alpha-1-antitrypsin deficiency severity

To be done before DR

**Comment by ljwh2** [comment]
@earlEBI has this been done?

**Comment by earlEBI** [comment]
yes

**Comment by ljwh2** [comment]
thanks
