### ISSUE TITLE
Clean up cohort data

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/xgwas-curator-tasks#20]
Cohort data needs cleaning up before sharing with users, e.g. all instances of UKB/UKBB to be harmonised, RSI-III to be combined, special characters removed.

@earlEBI  to add details here of what needs doing and @ljwh2 to follow up with developers.

**Comment by earlEBI** [comment]
**The following should be changed to 'UKB':**
- UKBB
- UK Biobank
- UKbiobank

**'others' should be 'other'**

**'multiple cohorts' should be 'multiple'**

**The following should all be changed to 'RS'**
- Rotterdam
- Rotterdam Study I
- Rotterdam Study II
- Rotterdam Study III
- RS_I
- RS_II
- RS_III
- RS1
- RS2
- RS3
- RSI
- RSII
- RSIII

**'GenScot' should be 'GS:SFHS'**

**Any commas within the cohort field should be changed to pipes**

**Any forward slashes within the cohort field should be changed to pipes**
- The only exception would be for the study (PMID 33414549) which gives a URL containing slashes: ("see cohorts in the educational attainment (excluding 23andMe) and cognitive performance GWAS by Lee et al. 2018 https://doi.org/10.1038/s41588-018-0147-3")
- It might be better to change the specific studies instead: 
    - (PMID 33547301 - 3 studies) - 'UKBB/BBJ'
    - (GCST90179151) - 'FTC/NAG-FIN'       
    
**Trailing spaces should be removed**

**'special characters' eg. 'Ôªø' should be removed**

**Note: Letter case should be disregarded when it comes to consolidating**

**Comment by earlEBI** [comment]
## Part 2 - smaller issues: 

**'All New Diabetics In Scania (ANDIS)' should be 'ANDIS'**

**'Malmö Diet and Cancer (MDC)' should be 'MDC'**

**'Children's Hospital of Philadelphia (CHOP)' should be 'CHOP'**

**'Baependi Heart Study' should be 'Baependi'**

**The following should be changed to 'Estonia'**:
- Estonia_Chip
- Estonia_WGS

**'EstBB' should be changed to 'EB'**

**'GenerationR' should be 'Generation_R'**

**The following should be 'GERA'**:
- GERA_EA_AFRchip
- GERA_EUR_LATchip
- The Resource for Genetic Epidemiology Research on Aging (GERA) Cohort

**Comment by ljwh2** [comment]
created dev ticket for this https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/gh/ebispot/goci/1111
