### ISSUE TITLE
Study with no p-value text

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/xgwas-curator-tasks#6]
Folkerson 28369058 has been published with no p-value text, even though there are association-level EFOs. 
https://www.ebi.ac.uk/gwas/curation/studies/55275858/associations 

As minimum, this needs recurating to include pvalue text. If time allows, we could take the opportunity to full recurate the paper as separate studies (including wrangling sumstats - they are split for trait already but also split by chr)

**Comment by ljwh2** [comment]
Decided not to split sumstats for now

**Comment by eks-ebi** [comment]
Have now added p-value text for each association, and republished the study. @ljwh2 This can now be closed.
