### ISSUE TITLE
Study with incorrect association level EFOs

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/xgwas-curator-tasks#7]
Ahsan 28915241 - there is a mismatch between the p text and association level EFOs. Looks like an error in the EFO to me, but needs checking. Could take the opportunity to split properly.

**Comment by Santhi1901** [comment]
This can't be edited in the depo-curation app as it was not added through the deposition app. Not able to submit a new submission in depo app as the status of the pmid is 'OPEN FOR SUMMARY STATISTICS SUBMISSION'. It needs dev to reopen the submission.

**Comment by Santhi1901** [comment]
split the submission into 39 studies->resubmitted it through the deposition app
GCST90274879 changed to original GCST: GCST009696

completed
